 name: docsify-action
  uses: tool3/docsify-action@v1.1
  with:
    # github access token
    github_token: 
    # destination dir
    dir: docs # optional, default is docs
    # destination branch
    branch: main # optional, default is master
    # docsify-cli args
    docsify_args: # optional
    # commit message used when pushing
    commit_msg: # optional, default is docs update 📚
